media:
  output: /blog/articles/images

collections:
  - name: blog
    label: ブログ記事
    type: folder
    path: blog/articles
    format: frontmatter       # 👈 html-frontmatter から標準の frontmatter に変更
    extension: md             # 👈 拡張子を明示的に .md（マークダウン）に指定
    slug: "{{title}}"

    fields:
      - name: title
        label: 記事のタイトル
        type: string
        required: true

      - name: date
        label: 公開日
        type: date
        required: true

      - name: body
        label: 記事の本文
        type: rich-text
        required: true
